server:
  port: 8082

spring:
  application:
    name: auth-server

  datasource:
    url: jdbc:postgresql://centerbeam.proxy.rlwy.net:34241/railway
    username: postgres
    password: HMroWPVhjEVmVdDIPhhPABBtEbBKirFd
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

# Configuración JWT
jwt:
  secret: ArkaSecretKeyForJWTTokenGenerationAndValidation2024!MustBeLongEnoughForHS256Algorithm
  expiration: 86400000 # 24 horas en milisegundos (24 * 60 * 60 * 1000)

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://52.72.28.32:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}

# Logging
logging:
  level:
    com.arka.auth_server: DEBUG
    org.springframework.security: DEBUG
