server:
  port: 8086

spring:
  application:
    name: cart-service

  data:
    mongodb:
      uri: ${SPRING_DATA_MONGODB_URI:mongodb://localhost:27017/arka_carts}
      auto-index-creation: true

# Eureka Client
eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_SERVER_URL:http://52.72.28.32:8761/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    prefer-ip-address: false
    hostname: ${spring.application.name}

# Actuator endpoints
management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus
  endpoint:
    health:
      show-details: always

# Logging
logging:
  level:
    com.arka.cart_service: DEBUG
    org.springframework.data.mongodb: DEBUG
