version: '3.8'

services:
  postgres:
    image: postgres:15-alpine
    container_name: arka-postgres
    environment:
      POSTGRES_DB: arka_products
      POSTGRES_USER: arka_user
      POSTGRES_PASSWORD: arka_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d

  postgres-auth:
    image: postgres:15-alpine
    container_name: arka-postgres-auth
    environment:
      POSTGRES_DB: arka_auth
      POSTGRES_USER: arka_user
      POSTGRES_PASSWORD: arka_password
    ports:
      - "5433:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data

  mongodb:
    image: mongo:6
    container_name: arka-mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: arka_admin
      MONGO_INITDB_ROOT_PASSWORD: arka_password
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  adminer:
    image: adminer
    container_name: arka-adminer
    ports:
      - "8080:8080"
    depends_on:
      - postgres

volumes:
  postgres_data:
  postgres_auth_data:
  mongodb_data: